version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: offboarding_postgres01
    restart: always
    ports:
      - "5567:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: offboarding_backend01
    ports:
      - "3951:3951"
    env_file:
      - ./Backend/server.env
    depends_on:
      - postgres

  frontend:
    build: ./Frontend
    container_name: offboarding_frontend01
    ports:
      - "9004:80"
    depends_on:
      - backend

  hr:
    build: ./HR
    container_name: offboarding_hr01
    ports:
      - "9005:80"
    depends_on:
      - backend

volumes:
  pgdata:

