version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: offboarding_postgres01
    restart: always
    ports:
      - "5200:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: offboarding_backend01
    ports:
      - "3100:3100"
    env_file:
      - ./Backend/server.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: offboarding_frontend01
    ports:
      - "8200:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr:
    build: ./HR
    container_name: offboarding_hr01
    ports:
      - "8201:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
